feat(xai): initial xai (grok) implementation
0xPlaygrounds/rig pull request #106
Opened 2024-11-14 07:47 UTC by 0xMochan

Implements xAI (grok) support.

## Notes
This implementation follows very closely to the openai implementation. It seems like xai has modeled their api to match both openai _and_ anthropic (simultaneously). The docs are very unclear on most of the sub-models so the implementation was essentially matched against openai. It might be possible to test alternative BASE_URLs schemas on the openai and anthropic APIs as suggested in the docs via python/js official SDK examples.

The `v1/embeddings` endpoint is documented and lists a model `v1` in the docs. Afaik, this is an internal model not available to the public as it's not listed as available in the xAI console (see photo). Therefore, this is untested (but likely would work if you had access to this model).

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/aa4e1924-b72a-4c72-a76c-89e14fc47b49">

2024-11-14 13:01 UTC, mateobelanger commented on rig-core/src/providers/xai/embedding.rs
> +// OpenAI Embedding API
```suggestion
// xAI Embedding API
```

2024-11-14 13:01 UTC, mateobelanger commented on rig-core/src/providers/xai/client.rs
> +// Google Gemini Client
```suggestion
// xAI Client
```

2024-11-14 13:04 UTC, mateobelanger reviewed
Can you add a reference to xAI in the readme's integration section? With the logo ideally!

2024-11-14 17:33 UTC, cvauclair requested changes
Nicely done! Only thing left is to clean up the main example (which is pretty messy atm) and addressing @mateobelanger 's comments.

Also, don't forget to add `xAI` to the list of providers in the repo README and the `rig-core/src/lib.rs` lib docstrings!

2024-11-19 01:43 UTC, 0xMochan commented
- Added general style comment changes
- Added xai to various READMEs
- Added some printlines to grok example

2024-11-19 16:22 UTC, cvauclair requested changes
Just a small thing to fix in the README and it should be good to go!

2024-11-19 16:22 UTC, cvauclair commented on rig-core/README.md
>  Additionally, Rig currently has the following integration sub-libraries:
This is missing a line break (renders as a single line rn)

2024-11-20 15:26 UTC, cvauclair approved these changes

2024-11-20 15:26 UTC, merged