feat: postgresql store
0xPlaygrounds/rig pull request #157
Opened 2024-12-18 14:36 UTC by milancermak

Resolves #5 

I've modeled the crate on the SQLite one.

On the DB side, the crate is relying on the [pgvector](https://github.com/pgvector/pgvector) extension. It creates an [HSNW index](https://github.com/pgvector/pgvector?tab=readme-ov-file#hnsw) and uses the cosine distane operator to compare embeddings.

Please let me know it this looks ok or if there are any parts of the code that should be changed.

2024-12-20 22:22 UTC, b0xtch commented
Hey great work, any update on this?

2024-12-21 00:04 UTC, 0xMochan commented
> Hey great work, any update on this?

I'm still in my review, I got wrapped up in some other responsibilities, will get it out ASAP!

2024-12-23 22:56 UTC, 0xMochan requested changes
Apologies for the delay on this review! Mostly looking good, a couple of changes I've requested here.

One note: I noticed that `'static` was used a good bit here which was likely inherited from the `sqlite` implementation. I think this is due to how the connection requires an closure with an async block which makes borrowing and using such things really odd.

Recently, proper [async closures](https://github.com/rust-lang/rust/pull/132706) which will get into Rust stable sometime in 2025 which should help us alleviate our usage of `'static` here (i think!)

2024-12-27 21:17 UTC, milancermak commented
Thanks for the review. I'm still in holiday mode until New Year's, will address the comments on Jan 2 or 3.

2025-01-03 10:08 UTC, milancermak commented on rig-postgres/examples/vector_search_postgres.rs
> +    // ).init();
Removing.

2025-01-03 10:25 UTC, milancermak commented on rig-postgres/src/lib.rs
> +            "INSERT INTO {} ({}) VALUES ({})",
This `format!` only builds the string from which the prepared statement is constructed. The output of the `format!` is sth like `INSERT INTO my_table_name (col1, col2, col3) VALUES ($1, $2, $3)`. So only the table and column names are interpolated in a unsafe, unescaped manner, but that doesn't matter because AFAIK the table would not be created in the first place (table and column names cannot contain sqli-friendly symbols like `'` or `;`).

As a side note, an agent-prompt-to-sqli attack is indeed an funny new attack vector 😆 In general, I think all this agent stuff will lead to amusing exploits 💀 

Optimistically resolving this convo.

2025-01-03 10:44 UTC, milancermak commented on rig-postgres/src/lib.rs
> +                .collect();
Good point. Adding an inline comment. Will leave this open, please close if you feel it's sufficient or let me know if I should add more detail.

2025-01-03 10:51 UTC, milancermak commented on rig-postgres/src/lib.rs
> +/// ```rust,ignore
Yes. I've added it because the code below needs ENV vars (DB URL and OpenAI API key), so it would break in CI. Is that ok? 

Alternatively, I guess I could set up a separate CI workflow only for this crate with psql running in docker.

2025-01-03 11:14 UTC, milancermak commented on rig-postgres/README.md
I presumed anyone using this crate already knows how to install, connect to and operate psql, but I've added a couple of sentences to address your comment.

2025-01-03 11:17 UTC, milancermak commented on rig-postgres/src/lib.rs
> +                }
IMO the original is easier to read.

2025-01-03 11:22 UTC, milancermak commented on rig-postgres/examples/vector_search_postgres.rs
> +    });
Short answer: I don't 100% know 😅 but that's the [recommended way](https://docs.rs/tokio-postgres/latest/tokio_postgres/index.html#example). Also [the docs](https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Connection.html) say

> should generally be spawned off onto an executor to run in the background

As far as I understand, the connection doesn't resolve until the work is done, so the code below wouldn't actually execute.

2025-01-03 11:24 UTC, milancermak commented
Hey @0xMochan ready for another round. I've addressed the comments you brought up, optimistically resolved the ones I think are done, but feel free to reopen if you think otherwise.

2025-01-03 17:48 UTC, 0xMochan commented on rig-postgres/src/lib.rs
> +/// ```rust,ignore
No this makes sense!

2025-01-06 18:59 UTC, 0xMochan approved these changes
Looks great, I've tested locally and it works fine for me. Thanks for this PR, will be included in the next release!

2025-01-06 18:59 UTC, 0xMochan commented on rig-postgres/README.md
> +The crate utilizes the [pgvector](https://github.com/pgvector/pgvector) extension, which is available for PostgreSQL version 13 and later. Use any of the [official](https://www.postgresql.org/downloa
In my testing, I had to go an add the `pgvector` extension myself. Not sure if I did something wrong, I had installed `postgres` via `brew`

2025-01-06 19:48 UTC, milancermak commented on rig-postgres/README.md
> +The crate utilizes the [pgvector](https://github.com/pgvector/pgvector) extension, which is available for PostgreSQL version 13 and later. Use any of the [official](https://www.postgresql.org/downloa
Huh, curious. You mean by brew installing it separately or something like that?

In any case, I guess the confusing term here in the README is "installed" - what I meant is that the crate will run `CREATE EXTENSION` which is the installation of the extension into the database, but of course there's also the installation of the extension library itself into the computer.

2025-01-08 10:37 UTC, milancermak commented
Rebased with upstream main, hopefully the CI will go green now 🤞

2025-01-08 17:36 UTC, milancermak commented
@caenguidanos All fair points.

As mentioned at the top, I've modeled this according to the sqlite crate. I'm not claiming it's the right abstraction (and you have good counterpoints why it's not), but it does help to get one started, as you indicated.

For someone like you who clearly knows what they're doing, this won't be the right abstraction to use. In fact, I don't think any will and it's better to plug in postgres to Rig in a way you see fit.

2025-01-13 17:09 UTC, milancermak commented
@cvauclair There's no easy way to address the comment from @caenguidanos in this PR, it would take a whole different approach and impl. That will have to be done by someone else. I initially built this for myself, but in a somewhat generic way similar to sqlite (as mentioned above). I've since reevaluated my approach and I'm doing stuff differently now and don't have the time to contribute. Feel free to reject this PR and do the integration as you see fit.

2025-01-14 20:54 UTC, b0xtch commented
> @cvauclair There's no easy way to address the comment from @caenguidanos in this PR, it would take a whole different approach and impl. That will have to be done by someone else. I initially built this for myself, but in a somewhat generic way similar to sqlite (as mentioned above). I've since reevaluated my approach and I'm doing stuff differently now and don't have the time to contribute. Feel free to reject this PR and do the integration as you see fit.

I agree, although sqlx is widely used this is a more than enough contribution to push through. Someone could claim diesel is better that’s not the point.

2025-01-16 11:49 UTC, carlos-verdes commented
Is there anyone picking up this?
I think it has not sense to do all features we want in a single PR, if this code is working as it is (with some hardcoded options) I think it can be published and then refactored to add more features (like choosing different algos).

I can try to get my hands into this.

2025-01-16 12:17 UTC, carlos-verdes commented
@milancermak can you allow me access to push into your branch so I can push some commits?
If not I can do PR on your branch, let me know what works best for you but I understand you are not going to be working on this now.

2025-01-16 12:24 UTC, milancermak commented
@carlos-verdes Please open a separate PR

2025-01-16 13:07 UTC, carlos-verdes commented
@milancermak I created first small PR fixing README and adding dotenvy for testing (using .env file).

I'm working on better Error handling now and removing that async block. 
Please take a look.

https://github.com/milancermak/rig/pull/1/files

2025-01-16 13:18 UTC, carlos-verdes commented
I didn't want to open a new PR, just use this one and update the code you started.

2025-01-16 13:29 UTC, carlos-verdes commented
Did you enable edits by maintainers @milancermak? 
I created a new PR based on this one as I can't add new commits here (permission denied): PR #208

2025-01-22 13:38 UTC, carlos-verdes commented
@oxmochan can you take a look at #231?

It's my first PR so please let me know if I have to add anything extra

@cvauclair your comments will be appreciated also

2025-01-27 19:59 UTC, closed without merging