refactor: remove DocumentEmbeddings from in memory vector store
0xPlaygrounds/rig pull request #53
Opened 2024-10-09 15:49 UTC by garance-buricatu

1. Refactor in memory vector store
2. Remove `VectorStore` trait
3. All other changes are side-effects of this

2024-10-10 15:44 UTC, cvauclair requested changes

2024-10-10 15:44 UTC, cvauclair commented on rig-core/examples/rag_dynamic_tools.rs
> +        .index(embedding_model);
This is not ideal, but would presumably get fixed in subsequent PR

2024-10-10 15:44 UTC, cvauclair commented on rig-core/src/vector_store/in_memory_store.rs
In this entire file, rename type parameter `D` to `T` to follow conventions (using other type parameter names is warranted when the type parameter has strict bounds, e.g.: `M: CompletionModel`, but in this case it's generic enough that `T` is more appropriate.

2024-10-10 15:44 UTC, cvauclair commented on rig-core/src/vector_store/in_memory_store.rs
> +    fn vector_search(&self, prompt_embedding: &Embedding, n: usize) -> EmbeddingRanking<D> {
Add unit tests for `vector_search` (at least one with multiple embeddings per item). 

Populate the store with fake embeddings with very few dimensions but make sure that are sensible. I.e.: Make the matching vectors close to each other (e.g.: `[0.1, 0.1, 0.5]` and `[0.1, 0.1, 0.6]`) and non-matching vectors away from each other (e.g.: `[0.1, 0.1, 0.5]` and `[-1.0, -0.6, 0.1]`)

2024-10-10 18:50 UTC, garance-buricatu commented on rig-core/src/vector_store/in_memory_store.rs
> +                .map(|Reverse(RankingItem(distance, id, _, embed_doc))| format!("{} ({}). Specific match: {}", id, distance, embed_doc))
Ok that makes sense but i though the whole point of having the document in the Embedding object was for debugging. So maybe i'll log it with tracing::debug! ?

2024-10-10 18:53 UTC, garance-buricatu commented on rig-core/src/vector_store/in_memory_store.rs
But T is already in use by `top_n` and `get_document`

2024-10-14 17:36 UTC, cvauclair commented on rig-core/src/vector_store/in_memory_store.rs
Ok, I think we'll change `VectorStoreIndex` to have a trait-level generic type anyway so this won't be a problem after that

2024-10-14 17:40 UTC, cvauclair requested changes

2024-10-14 17:40 UTC, cvauclair commented on rig-core/src/vector_store/in_memory_store.rs
> +                .map(|Reverse(RankingItem(distance, id, _, embed_doc))| format!("{} ({}). Specific match: {}", id, distance, embed_doc))
The user can decide to log the full document after generating the embedding if they want to inspect the data, but Rig shouldnt pollute the logs with large data dumps ourselves

2024-10-15 14:01 UTC, merged