docs(readme): test new logo coloration
0xPlaygrounds/rig pull request #79
Opened 2024-10-25 18:05 UTC by mateobelanger

2024-10-28 17:12 UTC, 0xMochan commented
<img width="551" alt="image" src="https://github.com/user-attachments/assets/c52349c8-d53d-4322-933b-e2507182b471">
interesting, i'm not sure about "By" not being aligned w/ "Playgrounds"

2024-10-29 18:57 UTC, mateobelanger commented
> <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/103326951/380816958-c52349c8-d53d-4322-933b-e2507182b471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjg0NTcsIm5iZiI6MTczMDIyODE1NywicGF0aCI6Ii8xMDMzMjY5NTEvMzgwODE2OTU4LWM1MjM0OWM4LWQ1M2QtNDMyMi05MzNiLWUyNTA3MTgyYjQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxODU1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmQ3OTg2ZDg4NjhiZTNhN2VlNmM3NmU5Mzg0ZWVmYzg1MGNiYjEzZDFlYjJlODZmZmYzYzY1ZjZiZmJkZjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rSUWEF__XCZgEkoinUinJHpzVvwlHlWKQSZRyx6qlZM">
> interesting, i'm not sure about "By" not being aligned w/ "Playgrounds". Otherwise, it's very nice!
@0xMochan 
Thanks for the feedback! Yeah bizarre quirk of svg because in my editor it's aligned. Will probably have to use png/jpeg.

2024-11-07 15:48 UTC, cvauclair requested changes
Nice work! But there are a few things to change. Also, the README example is outdated and should be: 
```rust
use rig::{completion::Prompt, providers::openai};

#[tokio::main]
async fn main() {
    // Create OpenAI client and model
    // This requires the `OPENAI_API_KEY` environment variable to be set.
    let openai_client = openai::Client::from_env();

    let gpt4 = openai_client.agent("gpt-4").build();

    // Prompt the model and print its response
    let response = gpt4
        .prompt("Who are you?")
        .await
        .expect("Failed to prompt GPT-4");

    println!("GPT-4: {response}");
}
```
(change `openai_client.model` to `openai_client.agent`)

2024-11-07 16:06 UTC, 0xMochan commented on README.md
>  &nbsp;
<img width="840" alt="image" src="https://github.com/user-attachments/assets/f55908ad-002f-4abd-8e5a-92b2532dd858">
This seems wrong / duplicates.., might want to clean this up

2024-11-07 20:20 UTC, merged